// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Delete' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.Delete(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.API.Models.ProductData}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'DeleteOption' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.DeleteOption(System.Guid,System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.API.Models.ProductOption}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'GetOptionById' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.GetOptionById(System.Guid,System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.IEnumerable{Xero.Product.API.Models.ProductOption}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'GetOptions' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.GetOptions(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.API.Models.ProductOptions}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'GetProductById' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.GetProductById(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.API.Models.ProductData}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'PostProduct' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.PostProduct(Xero.Product.API.Models.ProductData)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.API.Models.ProductData}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'PostProductOption' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.PostProductOption(System.Guid,Xero.Product.API.Models.ProductOption)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{Xero.Product.Domain.Domain.ProductOption}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Put' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.Put(System.Guid,System.Guid,Xero.Product.API.Models.ProductOption)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Put' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Controllers.ProductsController.Put(System.Guid,Xero.Product.API.Models.ProductData)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member Configure does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.API.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]