// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.AddProduct(Xero.Product.Data.Product)~System.Threading.Tasks.Task{Xero.Product.Data.Product}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetAllProducts(System.String)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{Xero.Product.Data.Product}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetProduct(System.Guid)~System.Threading.Tasks.Task{Xero.Product.Data.Product}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetOptions(System.Guid)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{Xero.Product.Data.ProductOption}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.AddProductOption(Xero.Product.Data.ProductOption)~System.Threading.Tasks.Task{Xero.Product.Data.ProductOption}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.UpdateProduct(System.Guid,Xero.Product.Data.Product)~System.Threading.Tasks.Task{Xero.Product.Data.Product}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.DeleteProductOption(System.Guid,System.Guid)~System.Threading.Tasks.Task{Xero.Product.Data.ProductOption}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.UpdateProductOption(System.Guid,System.Guid,Xero.Product.Data.ProductOption)~System.Threading.Tasks.Task{Xero.Product.Data.ProductOption}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetOptionById(System.Guid,System.Guid)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{Xero.Product.Data.ProductOption}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.AddProductOption(System.Guid,Xero.Product.Data.ProductOption)~System.Threading.Tasks.Task{Xero.Product.Data.ProductOption}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'void ProductContext.OnModelCreating(ModelBuilder builder)', validate parameter 'builder' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductContext.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.AddProduct(Xero.Product.Data.ProductData)~System.Threading.Tasks.Task{Xero.Product.Data.ProductData}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.DeleteProduct(System.Guid)~System.Threading.Tasks.Task{Xero.Product.Data.ProductData}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetAllProducts(System.String)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{Xero.Product.Data.ProductData}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetOptionById(System.Guid,System.Guid)~System.Threading.Tasks.Task{Xero.Product.Data.ProductOption}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.GetProduct(System.Guid)~System.Threading.Tasks.Task{Xero.Product.Data.ProductData}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.IsProductExist(System.Guid)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.IsProductOptionExist(System.Guid,System.Guid)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "<Pending>", Scope = "member", Target = "~M:Xero.Product.Data.ProductRepository.UpdateProduct(System.Guid,Xero.Product.Data.ProductData)~System.Threading.Tasks.Task{Xero.Product.Data.ProductData}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Options' to be read-only by removing the property setter.", Justification = "<Pending>", Scope = "member", Target = "~P:Xero.Product.Data.ProductData.Options")]